apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels" . | indent 4 }}
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true
